### ISSUE TITLE
Question: require vs dependency injection?

### ISSUE THREAD

**Issue by tobymurray** [focusaurus/express_code_structure#22]
I'm doing my first Node project, and coming from the Java world. The current project structure has, for example:
```
// index.js

app.use('/api', require('app/customers/router'))
```
and
```
// users/router.js

var router = require('express').Router()
var needUser = require('./need-user')

function signIn (req, res) {
  /* eslint no-unused-vars:0 */
  // ...
}

function profile (req, res) {
  res.render('users/profile')
}

router.post('/users/sign-in', signIn)
router.get('/users/profile', needUser, profile)

module.exports = router
```

The repetition of `var router = require('express').Router()` in each of the routers doesn't look particularly appealing to me . What are your thoughts (pros/cons of each method) about going with a more "dependency injection" style approach, like the following:

```
// index.js

const router = express.Router();
app.use('/api', require('app/customers/router')(router))
```

```
// users/router.js

var needUser = require('./need-user')

module.exports = function (router) {
  function signIn(req, res) {
    /* eslint no-unused-vars:0 */
    // ...
  }

  function profile(req, res) {
    res.render('users/profile')
  }

  router.post('/users/sign-in', signIn)
  router.get('/users/profile', needUser, profile)

  return router;
}
```

I think this ends up being functionally the same (again, I'm new, so maybe I'm mistaken) but gets rid of the need to `require` everywhere. Additionally, perhaps not relevant for the router, but for something like a database tool it allows for easier testing as a mock object can be thrown in instead in the test code.

I'm looking for best practices for my own project, and while it's interesting that ExpressJS is unopinionated, that leaves a void for terrible project structure to thrive. I agree with a lot of the opinions you've expressed here, so I'm interested to see what you think of the code above.

**Comment by focusaurus** [comment]
> about going with a more "dependency injection" style approach, like the following:

I used to do something like that before express support for modular routers was as full-featured as it is now. Now I prefer modular subapps with their own router for cleaner isolation.

> but gets rid of the need to require everywhere.

I can understand this sentiment, but in my experience it's an anti-pattern. The custom dependency injection API you are creating here adds very little actual value vs node standard commonjs which is fully understood by the community and lots of tooling for mocking and testing. I'd invite you to clarify "doesn't look particularly appealing" for yourself. Why not? Does your version have less boilerplate? I don't think so, and the boilerplate function is more error-prone and a custom one-off interface which is likely undocumented.

Having worked with AngularJS's disasterous DI system and projects that find boilerplate `require` statements "not appealing" so they do stuff like `global.lodash = require('lodash');` somewhere early during app initialization (thus creating an implicit load order dependency), I'm of the opinion that regular, modular CommonJS files with no implicit load order dependencies that can be run as standalone node programs are a superior structure. Even though there's some repetition, the explicit deps using the community's primary mechanism are worth it for me.

In node I find sinon sandboxes usually fine for mocking databases and if things get really hairy I'll reach for something like `rewire` or `proxy-require` but I'd rather just make a `db.js` commonjs module and use sinon to sandbox the `db.lookupUser(42, callback);` call as opposed to using a dependency injection pattern.

It's not that DI itself doesn't seem useful to me, it's just that if I'm going to use it, I want it baked into the programming language itself where it belongs, not tacked on with a hacky userland system.

**Comment by tobymurray** [comment]
> It's not that DI itself doesn't seem useful to me 

I've used [Dagger](https://google.github.io/dagger/) in an enterprise Java application, and I thought it was wonderful. It sucks when the graph gets huge, but having run into enough global singletons it seems far better than the alternatives I'm aware of.

> I'd invite you to clarify "doesn't look particularly appealing" for yourself. Why not?

Biggest reason in Java world would be testing, although I admit I'm completely unfamiliar with the technologies you mentioned. With the ability to monkey patch, perhaps that's irrelevant in JavaScript - I'll take a look! Secondly though, and I think still relevant here, is as a layer of abstraction between dependencies and the functionality that depends on them. The router is probably a terrible example for me to use, but imagining I wanted to use a different router it'd suck to have to go to all the separate files and change them all vs. changing in one place.

> it's just that if I'm going to use it, I want it baked into the programming language itself where it belongs, not tacked on with a hacky userland system.

What do you mean by a "hacky userland system"? Isn't it just how `require` works - you can provide arguments to it? Are you referring to where the dependencies are initialized, and how there's no tooling to support or enforce them/actually do the "injection" part of the DI? Is it meaningfully different from the `app.use` functionality for middleware?

> Now I prefer modular subapps with their own router for cleaner isolation.

Is the sentiment here something along the lines of you being able to take a subdirectory out and drop it in its own application and run more effectively "as is"? What's the isolation in this case refer to - does it make sense for every object that adds a route to create its own router? Isn't that not respecting a separation of concerns?

> Having worked with AngularJS's disasterous DI system

Is that Angular 1? I've used Angular 2 and it seems pretty straightforward and usable, although I've only used it on smaller applications. 

--- 
Completely separately, how do you share resources that require initialization - e.g. a database connection  pool with something like [Knex](http://knexjs.org/)) if you need access in all of the model files like `need-user.js`. I don't see an example of that in this project structure - if you have some insight, I'd be up for doing up a PR to incorporate an example into this project.

Thanks so much for your response! Great to get an opinion from someone who's been immersed in the ecosystem for a long time.

**Comment by tobymurray** [comment]
> I'd invite you to clarify "doesn't look particularly appealing" for yourself. Why not?

To elaborate on that, how is this different from the motivation that lead to DI and IoC in the first place? If the lower level class/modules/whatever are creating their own dependencies, isn't that essentially just the whole "global state" issue? It looks like transitive dependencies are implicit, and scaling up complexity wise (into mid-size app territory) means it's not clear what's actually going on at any particular point - if one class/module/whatever requires a bunch of others, and you monkey-patch a dependency in one place how do you intercept all the other `require` calls?

**Comment by focusaurus** [comment]
> The router is probably a terrible example for me to use, but imagining I wanted to use a different router it'd suck to have to go to all the separate files and change them all vs. changing in one place.

Indeed. I'm not very concerned about this. I don't want a database abstraction. If I change databases, I change my code and a lot of it at that and that's OK. It's better than the impedence mismatch and API obfuscation of trying to use a generic database (or router in this case) API instead of just a concrete one.

I tend to be pragmatic though so these concerns may be very much valid but they don't resonate with me. Keep things small and easy to change instead of trying to build abstractions. Use tests to  allow refactoring without regression, not abstractions and design patterns.

> it'd suck to have to go to all the separate files and change them all vs. changing in one place.

Not for me. There's not going to be 100s of files. Dozens at most. I'm good with my text editor and unix tools. If the change is mechanical I'd be done in minutes. I'm not afraid of changing the code, especially if it is a mechanical operation without a lot of ways to make subtle mistakes.

> What do you mean by a "hacky userland system"? Isn't it just how require works - you can provide arguments to it? Are you referring to where the dependencies are initialized, and how there's no tooling to support or enforce them/actually do the "injection" part of the DI? Is it meaningfully different from the app.use functionality for middleware?

Basically I mean commonjs is what node uses and introducing something else doesn't seem worth it to me given the other options available in a dynamic language such as JS. I do "node-style" node meaning commonjs, callbacks, no transpilers, etc.

I'm saying if you use newrelic or similar APM tooling, they are going to "just work" out of the box with commonjs. Same for bundlers like browserify or webpack. These and other tools may or may not be compatible with some other system for dependencies.

As for `app.use` middleware dependencies this is in fact one of my biggest gripes with express/connect. I'd much rather be able to explicitly specify that my session middleware depends on the cookie parsing middleware having run first. If they had followed the spirit of commonjs, each middleware would declare its dependencies, but they didn't, and thus many express apps break when middleware are configured out of order.


> Is the sentiment here something along the lines of you being able to take a subdirectory out and drop it in its own application and run more effectively "as is"? What's the isolation in this case refer to - does it make sense for every object that adds a route to create its own router? Isn't that not respecting a separation of concerns?

Somewhat but mostly it's about understanding behavior and grouping of related or interdependent things. If I didn't enable compression middleware in my router, I don't want to see the application unexpectedly just do that for me. I don't want my `req.params` pre-parsed into some app-specific data structure by some other middleware implicitly required. Instead of having each sub-router have `// FYI the main app turns on compression` I'd rather just see the 1-liner of code that means the same `router.use(compression());`.

And no I don't need one router for every route, but one router for each group of tightly-coupled or closely-related routes. Each logical subsystem if you will.

But I see what you're getting at and there's tradeoffs for both the "combine independent routers" into an app approach and the "routers are like plugins that just do this one little bit" approach.

> To elaborate on that, how is this different from the motivation that lead to DI and IoC in the first place? If the lower level class/modules/whatever are creating their own dependencies, isn't that essentially just the whole "global state" issue? It looks like transitive dependencies are implicit, and scaling up complexity wise (into mid-size app territory) means it's not clear what's actually going on at any particular point - if one class/module/whatever requires a bunch of others, and you monkey-patch a dependency in one place how do you intercept all the other require calls?

I make a distinction here in that I code in a stateless module style so when I `require` something, that something isn't usually a stateful thing like a DB connection pool. It's just a set of code I run. If I need something stateful, I initialize that once at the periphery of the app and it gets made available via some "ambient" mechanism as Rich Hickey would say. I don't think this is ideal, but for me in node.js a DI/IoC solution is worse than the problem.

I don't intercept require calls, I intercept runtime calls. So instead of intercepting `require('db')`, I intercept `db.getUser(42, callback);`. Intercepting require calls I'll only do when my hand is forced by some third party module's design.


 >Completely separately, how do you share resources that require initialization - e.g. a database connection pool with something like Knex) if you need access in all of the model files like need-user.js. I don't see an example of that in this project structure - if you have some insight, I'd be up for doing up a PR to incorporate an example into this project.

I don't do anything special for that. I usually follow the same pattern you see in the docs for that module. Typically these are ultimately app-wide shared state or perhaps I'd stick them onto `app.locals` or `res.locals` in express as needed.

In terms of scope, I'm drawing the line for this project mostly about your directory and file layout. Once you start talking about the content of `.js` files in detail, scope goes through the moon.

**Comment by tobymurray** [comment]
Awesome! Thanks so much for taking the time to respond, I definitely appreciate your feedback. You've cleared up a lot of questions I've had, and there seem to be far more beginners than advanced developers in the JS realm so it's hard to know who actually has any idea. I think you're on to one of the key factors though - Node projects generally don't stretch to the thousands of files so any additional complexity has to pay off over a far smaller number of files.

> I'd much rather be able to explicitly specify that my session middleware depends on the cookie parsing middleware having run first

Agreed, I've already run into this a couple times. Designing things the "best" way is hard!

> If I need something stateful, I initialize that once at the periphery of the app and it gets made available via some "ambient" mechanism as Rich Hickey would say. I don't think this is ideal, but for me in node.js a DI/IoC solution is worse than the problem.

This seems like an area where people tend to just kind of go for it, I've been struggling to find how people deal with it. The whole "don't pollute the global namespace" practices of client side JS and best practices in other languages lead me to be a bit gun shy to do so. Handling "stateful" dependencies separately from "stateless" dependencies definitely makes a lot of sense to me though.

**Comment by focusaurus** [comment]
Just keep in mind I never pollute the global namespace, but I do share modules. So I might have a `db.js` module with a `db.connect(params)` that initializes a connection poll at the start of the app and uses that for queries when call to `db.find(query)` are made. So it's still shared state but it's still imported with commonjs `require` and not a global variable.
