### ISSUE TITLE
Integration Tests

### ISSUE THREAD

**Issue by nickfaughey** [focusaurus/express_code_structure#28]
This directory structure is a great way to organize code and unit tests, but breaks down slightly when it comes to integration tests. Any suggestions for where to store integration tests? For example, a test that adds a [Customer](https://github.com/focusaurus/express_code_structure/blob/master/app/customers/customer-model.js) and links it to a [Deal](https://github.com/focusaurus/express_code_structure/tree/master/app/deals) doesn't really have a logical directory to live in. Any suggestions for the cleanest way to add these into the directory structure?

**Comment by focusaurus** [comment]
I actually still follow the same principle, which is group by coupling and don't reach out to a sibling directory. So that means if code is coupled to the entire running application, it belongs in the `app` directory. For example, for my web site, the integration test code lives at [app/integration-tests.js](https://github.com/focusaurus/peterlyons.com/blob/develop/app/integration-tests.js). If you have a lot of them, make subdirectories as needed according to the same guidelines.

**Comment by focusaurus** [comment]
Updated the README to address this topic in v3.1.0. Thanks!

**Comment by focusaurus** [comment]
Oh one more note that I think the [test organization described by the rust book](http://rust-lang.github.io/book/second-edition/ch11-03-test-organization.html) is really good.
